version: '3.8'
services:
  mongodb:
    image: mongo
    platform: linux/x86_64
    ports: ['27017:27017']
    env_file: ./.env

  api:
    depends_on:
     - mongodb
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    container_name: api
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=$MONGO_INITDB_DATABASE
      - spring.data.mongodb.username=$MONGO_INITDB_ROOT_USERNAME
      - spring.data.mongodb.password=$MONGO_INITDB_ROOT_PASSWORD
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

